const whats = "https://wa.me/5511968112100";

export default function Home() {
  return <main>
    <style>{`*{box-sizing:border-box}body{margin:0;background:#e9e4d8;color:#11221f;font-family:Arial,sans-serif}main{overflow:hidden}.top{display:flex;justify-content:space-between;padding:26px 7%;font-weight:700}.brand{font-family:Georgia,serif;font-size:24px}.hero{min-height:650px;display:grid;grid-template-columns:1.05fr .95fr;align-items:center;gap:54px;padding:60px 9%;background:#e9e4d8}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:12px;font-weight:700;color:#866c45}h1,h2{font-family:Georgia,serif;line-height:1.05;margin:.35em 0}h1{font-size:clamp(42px,6vw,76px)}h1 i{font-weight:400}h2{font-size:clamp(34px,4vw,56px)}p{font-size:17px;line-height:1.65;max-width:650px}.portrait{position:relative}.portrait img{width:100%;max-height:560px;object-fit:cover;filter:grayscale(1)}.oab{position:absolute;right:-26px;bottom:-22px;background:#fff;padding:23px;text-align:center;line-height:1.45}.button{display:inline-block;margin-top:18px;padding:16px 23px;background:#183b34;color:#fff;text-decoration:none;font-weight:700}.section{padding:90px 9%;background:#f8f6f0}.muted{background:#d5c7ad}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:35px}.card{padding:26px;border-top:2px solid #b69c72;background:#fff}.card span{color:#866c45;font-weight:700}.card h3{font-family:Georgia,serif;font-size:25px;margin:15px 0}.contact{padding:90px 9%;background:#183b34;color:#fff;display:grid;grid-template-columns:1fr 1fr;gap:60px}.contact .eyebrow{color:#d8bf91}.contact a{color:#fff}.footer{padding:25px 9%;background:#102822;color:#fff}@media(max-width:700px){.top,.hero,.contact{display:block}.top a:last-child{display:none}.hero{padding:45px 7%}.portrait{margin-top:40px}.oab{right:0}.section,.contact{padding:65px 7%}.grid{grid-template-columns:1fr}}`}</style>
    <header className="top"><span className="brand">Dantas &amp; Advogados</span><a href={whats}>WhatsApp: (11) 96811-2100</a></header>
    <section className="hero"><div><p className="eyebrow">Dantas &amp; Advogados Associados</p><h1>Assessoria jurÃ­dica com <i>clareza e estratÃ©gia.</i></h1><p>Atendimento jurÃ­dico personalizado para pessoas fÃ­sicas e empresas, com atuaÃ§Ã£o presencial e online.</p><p>O escritÃ³rio atua hÃ¡ mais de 14 anos oferecendo orientaÃ§Ã£o e representaÃ§Ã£o jurÃ­dica em demandas cÃ­veis, trabalhistas, criminais e de famÃ­lia.</p><a className="button" href={whats}>Falar com o escritÃ³rio no WhatsApp â†’</a></div><div className="portrait"><img src="https://www.advogadoemcotia.com.br/assets/images/preto-e-branco-640x684.jpg" alt="Dr. Ivan Souza Dantas"/><div className="oab">OAB/SP<br/><b>303.195</b></div></div></section>
    <section className="section"><p className="eyebrow">Como podemos auxiliar</p><h2>AtuaÃ§Ã£o jurÃ­dica para o que importa agora.</h2><div className="grid">{[["01","Direito Civil","Contratos, cobranÃ§as, indenizaÃ§Ãµes e direito do consumidor."],["02","Direito do Trabalho","Assessoria para empregados e empregadores."],["03","Direito Penal e FamÃ­lia","Defesa tÃ©cnica e orientaÃ§Ã£o individualizada."]].map(([n,t,d]) => (<article className="card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>))}</div></section>
    <section className="section muted"><p className="eyebrow">Sobre o advogado</p><h2>Ivan Souza Dantas</h2><p>Advogado inscrito na OAB/SP sob nÂº 303.195 e responsÃ¡vel pelo Dantas &amp; Advogados Associados. Atendimento em Cotia, Itapevi, Baixada Santista e online.</p></section>
    <section className="contact"><div><p className="eyebrow">Entre em contato</p><h2>Seu caso merece atenÃ§Ã£o.</h2><p>Fale com o escritÃ³rio para receber as orientaÃ§Ãµes iniciais sobre o seu atendimento.</p><a className="button" href={whats}>Falar pelo WhatsApp â†’</a></div><div><p><b>Telefone e WhatsApp</b><br/>(11) 96811-2100</p><p><b>E-mail</b><br/>ivan_advogado@hotmail.com</p><p><b>EndereÃ§o em Cotia</b><br/>Av. Prof. Manoel JosÃ© Pedroso, 1695, Sala 4<br/>Parque Bahia â€” Cotia/SP</p></div></section><footer className="footer">Â© {new Date().getFullYear()} Dantas &amp; Advogados Associados</footer>
  </main>;
}

